services:
  db:
    image: postgres:alpine3.20
    restart: always
    environment:
      POSTGRES_USER: project_dev
      POSTGRES_PASSWORD: project_dev_password
      POSTGRES_DB: go_clean
    volumes:
      - db_dbo:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  db_dbo:
